# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Numpy-Introduction" data-toc-modified-id="Numpy-Introduction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy Introduction</a></div><div class="lev2 toc-item"><a href="#Numpy-Array" data-toc-modified-id="Numpy-Array-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Numpy Array</a></div><div class="lev3 toc-item"><a href="#Create-a-numpy-array" data-toc-modified-id="Create-a-numpy-array-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Create a numpy array</a></div><div class="lev3 toc-item"><a href="#Accessing-Array-Elements" data-toc-modified-id="Accessing-Array-Elements-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Accessing Array Elements</a></div><div class="lev3 toc-item"><a href="#Copying-and-Editing-Array-Elements" data-toc-modified-id="Copying-and-Editing-Array-Elements-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Copying and Editing Array Elements</a></div><div class="lev2 toc-item"><a href="#Basic-Operations" data-toc-modified-id="Basic-Operations-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Basic Operations</a></div><div class="lev3 toc-item"><a href="#Add-and-multiply-array-elements-with-a-scalar" data-toc-modified-id="Add-and-multiply-array-elements-with-a-scalar-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Add and multiply array elements with a scalar</a></div><div class="lev3 toc-item"><a href="#Elementwise-addition-and-multiplication-of-matrices-of-the-same-size" data-toc-modified-id="Elementwise-addition-and-multiplication-of-matrices-of-the-same-size-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Elementwise addition and multiplication of matrices of the same size</a></div><div class="lev3 toc-item"><a href="#Some-other-elementwise-operations:" data-toc-modified-id="Some-other-elementwise-operations:-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Some other elementwise operations:</a></div><div class="lev3 toc-item"><a href="#Dot-product" data-toc-modified-id="Dot-product-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>Dot product</a></div><div class="lev3 toc-item"><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-1.2.5"><span class="toc-item-num">1.2.5&nbsp;&nbsp;</span>Matrix multiplication</a></div><div class="lev3 toc-item"><a href="#Simple-statistic-operations-on-arrays" data-toc-modified-id="Simple-statistic-operations-on-arrays-1.2.6"><span class="toc-item-num">1.2.6&nbsp;&nbsp;</span>Simple statistic operations on arrays</a></div><div class="lev2 toc-item"><a href="#Stacking-and-splitting-arrays" data-toc-modified-id="Stacking-and-splitting-arrays-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Stacking and splitting arrays</a></div><div class="lev2 toc-item"><a href="#Ordering-array-elements" data-toc-modified-id="Ordering-array-elements-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Ordering array elements</a></div><div class="lev2 toc-item"><a href="#Array-Query" data-toc-modified-id="Array-Query-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Array Query</a></div><div class="lev2 toc-item"><a href="#Import-and-Export-Data-from/to-Files" data-toc-modified-id="Import-and-Export-Data-from/to-Files-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Import and Export Data from/to Files</a></div><div class="lev2 toc-item"><a href="#Exercises" data-toc-modified-id="Exercises-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Exercises</a></div>

[Go to Workshop Overview (.ipynb)](Overview.ipynb) / [[.html]](Overview.html)

# Numpy Introduction

In [1]:
import numpy as np
print np.__version__

1.11.1


## Numpy Array
In Numpy arrays are the main type of objects. In arrays elements are arranged in multidimensional tables. Array elements are indexed by positive integers, starting at 0.
### Create a numpy array
Create a 1-dimensional array and access its type, number of dimensions and shape and size:

In [2]:
A=np.array([1,2,3.0])
print A
print "Type of variable:     ",type(A)
print "Type of elements:     ",A.dtype
print "Number of dimensions: ",A.ndim
print "Shape:                ",A.shape
print "Size:                 ",A.size

[ 1.  2.  3.]
Type of variable:      <type 'numpy.ndarray'>
Type of elements:      float64
Number of dimensions:  1
Shape:                 (3L,)
Size:                  3


Create a 2-dimensional array and access its type, number of dimensions and shape and size:

In [53]:
B=np.array([[1,2,3,4],[5,6,0,1],[1,2,0,1]])
print B
print "Type of variable:     ",type(B)
print "Type of elements:     ",B.dtype
print "Number of dimensions: ",B.ndim
print "Shape:                ",B.shape
print "Size:                 ",B.size

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]
Type of variable:      <type 'numpy.ndarray'>
Type of elements:      int32
Number of dimensions:  2
Shape:                 (3L, 4L)
Size:                  12


Create 2-dimensional array of zeros:

In [4]:
Z=np.zeros((5,2))
print Z

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


Create a 3-dimensional array of ones

In [5]:
O=np.ones((2,3,4))
print O

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]


Create 2-dimensional array of random integers between 10 (inclusive) and 20 (exclusive)

In [6]:
RI=np.random.randint(10,20,(5,3))
print RI

[[13 11 15]
 [10 17 12]
 [10 15 19]
 [19 11 16]
 [16 13 17]]


Create a 2-dimensional array of random numbers according to a Gaussian normal distribution with mean 0 and standard deviation 1.

In [7]:
RN=np.random.randn(2,5)
print RN

[[ 0.87254221  1.06819424  1.12431665  0.40382727 -0.24675147]
 [ 1.53358115  1.56698618  0.59372411 -0.90843256 -1.38829156]]


Create a 2-dimensional array of random numbers according to a Gaussian normal distribution with mean m=100 and standard deviation s=5.

In [8]:
mean=100
sigma=5
RN100=sigma*np.random.randn(4,8)+mean
print RN100

[[ 100.07707471  101.84813836  103.0184653    92.43587465  103.24532678
   102.22788652  103.68939813   99.62573556]
 [  91.66693982   96.73652453  102.16169247   91.74888463   92.3486966
   102.84504655   89.88227636  101.13780415]
 [  99.24027107   96.15484432  100.24975972   96.05696283   93.60916686
   103.35345763   95.02667983  100.18886741]
 [  95.94167667  101.22416001  101.44792433  107.73864644   95.09023675
    92.83481419   99.09648723   96.7444766 ]]


Set print options, such that only 2 positions after the decimal point are printed.

In [9]:
np.set_printoptions(precision=2)
print RN100

[[ 100.08  101.85  103.02   92.44  103.25  102.23  103.69   99.63]
 [  91.67   96.74  102.16   91.75   92.35  102.85   89.88  101.14]
 [  99.24   96.15  100.25   96.06   93.61  103.35   95.03  100.19]
 [  95.94  101.22  101.45  107.74   95.09   92.83   99.1    96.74]]


Throw a balanced dice for 30 times. The first element of the resulting array is the number of times a 1 has been thrown, the last element is the number of times a 1 has been thrown.   

In [10]:
RM=np.random.multinomial(30,[1/6.]*6)
print RM

[3 6 4 5 7 5]


Create a 1-dimensional array, containing a sequence of numbers, starting from 2, terminating before 18 and a stepzize of 4.  

In [11]:
S=np.arange(2,18,4)
print S

[ 2  6 10 14]


Reshape the 1-dimensional array to a 2-dimensional array. Note that the number of elements in the original and the reshaped array must be equal.

In [12]:
SR = S.reshape((2,2))
print SR

[[ 2  6]
 [10 14]]


In the _reshape()_ function the last shape-element need not be specified. It is enough to place a _-1_ at the corresponding position. Then this shape-element is calculated from the other shape-elements and the number of elements in the array. Below another _reshape()_ is performed. Note that the result is a _2-dimensional array_ of 1 row and 4 columns. 

In [13]:
SRR=SR.reshape((1,-1))
print SRR

[[ 2  6 10 14]]


The _flatten()_ function yields a _1-dimensional_ array.

In [54]:
SRRR=SR.flatten()
print SRRR

[ 2  6 10 14]


### Accessing Array Elements

In [55]:
print B

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]


Access the element in the first row and third column:

In [56]:
b=B[0,2]
print b

3


Access the second row:

In [57]:
r=B[1,:]
print r

[5 6 0 1]


Access the first column:

In [58]:
c=B[:,0]
print c

[1 5 1]


Access elements 2 and 3 of the second column:

In [59]:
p=B[1,1:3]
print p

[6 0]


Access the lower right (2x2) subarray of B:

In [60]:
l=B[1:,2:]
print l

[[0 1]
 [0 1]]


Negative integers can be applied to access array elements in the reverse order. E.g. B[-1,:] is the last row of B. Thus the lower right (2x2) subarray of B can also be obtained by:

In [61]:
l2=B[-2:,-2:]
print l2

[[0 1]
 [0 1]]


Reversing columns and rows in an array:

In [62]:
RB=B[::-1,::-1]
print "B=\n",B
print "Reverse order of columns and rows:\nRB=\n",RB

B=
[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]
Reverse order of columns and rows:
RB=
[[1 0 2 1]
 [1 0 6 5]
 [4 3 2 1]]


In [63]:
a=10*np.arange(10)
idx=np.array([1,9,3])
print a
print a[idx]

[ 0 10 20 30 40 50 60 70 80 90]
[10 90 30]


### Copying and Editing Array Elements

Copy B to CB:

In [64]:
CB=B
print CB

[[1 2 3 4]
 [5 6 0 1]
 [1 2 0 1]]


Editing part of B:

In [65]:
B[1:,2:]=np.zeros((2,2))
print "B=\n",B
print "CB=\n",CB

B=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]
CB=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]


As shown above copying by __=__ is a shallow copy. A **deep copy** can be implemented as follows:

In [66]:
CB=B.copy()
B[1:,2:]=np.ones((2,2))
print "B=\n",B
print "CB=\n",CB

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
CB=
[[1 2 3 4]
 [5 6 0 0]
 [1 2 0 0]]


## Basic Operations

### Add and multiply array elements with a scalar

In [67]:
print B

[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [68]:
print 3*B

[[ 3  6  9 12]
 [15 18  3  3]
 [ 3  6  3  3]]


In [69]:
print 100+B

[[101 102 103 104]
 [105 106 101 101]
 [101 102 101 101]]


### Elementwise addition and multiplication of matrices of the same size

In [70]:
A=np.random.randint(0,7,B.shape)
print "B=\n",B
print "A=\n",A

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
A=
[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


In [71]:
S=A+B
print S

[[3 5 3 5]
 [9 8 7 1]
 [6 3 7 3]]


In [72]:
P=A*B
print P

[[ 2  6  0  4]
 [20 12  6  0]
 [ 5  2  6  2]]


### Some other elementwise operations:

In [73]:
P2=B**2
print "All elements of B raised to a power of 2\n P2=\n",P2

All elements of B raised to a power of 2
 P2=
[[ 1  4  9 16]
 [25 36  1  1]
 [ 1  4  1  1]]


In [74]:
SR=np.sqrt(B)
print "Elementwise squareroot\n SR=\n",SR

Elementwise squareroot
 SR=
[[ 1.    1.41  1.73  2.  ]
 [ 2.24  2.45  1.    1.  ]
 [ 1.    1.41  1.    1.  ]]


In [75]:
SI=np.sin(B)
print "Elementwise sine\n SI=\n",SI

Elementwise sine
 SI=
[[ 0.84  0.91  0.14 -0.76]
 [-0.96 -0.28  0.84  0.84]
 [ 0.84  0.91  0.84  0.84]]


### Dot product

In [76]:
a=np.arange(3)
b=np.array([2,4,1])
print a
print b

[0 1 2]
[2 4 1]


In [77]:
c=np.dot(a,b)
print c

6


### Matrix multiplication

In [78]:
print "B=\n",B
print "A=\n",A

B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]
A=
[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


In [79]:
C=np.dot(A,B)
print "C=\n",C

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [109]:
BT=np.transpose(B)
print "BT=\n",BT
C=np.dot(A,BT)
print "C=\n",C

BT=
[[1 5 1]
 [2 6 2]
 [3 1 1]
 [4 1 1]]
C=
[[12 29  9]
 [26 38 14]
 [33 39 15]]


In [110]:
BT2=A.dot(BT)
print "BT2=\n",BT2

BT2=
[[12 29  9]
 [26 38 14]
 [33 39 15]]


### Simple statistic operations on arrays

In [111]:
print "A=\n",A 

A=
[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


In [112]:
print "Minimum = %3d\nMaximum = %3d\nMean = %3.2f"%(A.min(),A.max(),A.mean())

Minimum =   0
Maximum =   6
Mean = 2.67


In [113]:
print "Minimum = %s\nMaximum = %s\nMean = %s"%(A.min(axis=0),A.max(axis=0),A.mean(axis=0))

Minimum = [2 1 0 0]
Maximum = [5 3 6 2]
Mean = [ 3.67  2.    4.    1.  ]


In [114]:
print "Minimum = %s\nMaximum = %s\nMean = %s"%(A.min(axis=1),A.max(axis=1),A.mean(axis=1))

Minimum = [0 0 1]
Maximum = [3 6 6]
Mean = [ 1.5  3.   3.5]


## Stacking and splitting arrays 

In [115]:
print "A=\n",A
print "B=\n",B

A=
[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]
B=
[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [116]:
V=np.vstack((A,B))
print "V=\n",V

V=
[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]
 [1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [117]:
H=np.hstack((A,B))
print "H=\n",H

H=
[[2 3 0 1 1 2 3 4]
 [4 2 6 0 5 6 1 1]
 [5 1 6 2 1 2 1 1]]


In [118]:
Hs=np.hsplit(H,(3,5))
print "1st part=\n",Hs[0]
print "2nd part=\n",Hs[1]
print "3rd part=\n",Hs[2]

1st part=
[[2 3 0]
 [4 2 6]
 [5 1 6]]
2nd part=
[[1 1]
 [0 5]
 [2 1]]
3rd part=
[[2 3 4]
 [6 1 1]
 [2 1 1]]


In [119]:
Vs=np.vsplit(V,(2,))
print "1st part=\n",Vs[0]
print "2nd part=\n",Vs[1]

1st part=
[[2 3 0 1]
 [4 2 6 0]]
2nd part=
[[5 1 6 2]
 [1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


## Ordering array elements

In [120]:
b=np.random.randint(0,100,15)
print b

[27 66 93 62 20  4 29 91 54  4 94 47 51 95 98]


In [121]:
bs=np.sort(b)
print bs

[ 4  4 20 27 29 47 51 54 62 66 91 93 94 95 98]


In [122]:
sortIdx=np.argsort(b)
print sortIdx

[ 5  9  4  0  6 11 12  8  3  1  7  2 10 13 14]


In [123]:
bss=b[sortIdx]
print bss

[ 4  4 20 27 29 47 51 54 62 66 91 93 94 95 98]


## Array Query

In [124]:
print A

[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


In [125]:
print A.nonzero()

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 3, 0, 1, 2, 0, 1, 2, 3], dtype=int64))


In [126]:
print np.where(A>2)

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 0, 2, 0, 2], dtype=int64))


In [127]:
print np.where(A>2,np.ones(A.shape),np.zeros(A.shape))

[[ 0.  1.  0.  0.]
 [ 1.  0.  1.  0.]
 [ 1.  0.  1.  0.]]


In [128]:
print A

[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


In [129]:
print B

[[1 2 3 4]
 [5 6 1 1]
 [1 2 1 1]]


In [130]:
print A>B

[[ True  True False False]
 [False False  True False]
 [ True False  True  True]]


In [131]:
print np.any(A>B,axis=0)

[ True  True  True  True]


In [132]:
print np.any(A>B,axis=1)

[ True  True  True]


In [133]:
print np.all(A>B,axis=0)

[False False False False]


In [134]:
print np.all(A>B,axis=1)

[False False False]


## Import and Export Data from/to Files 

In [135]:
print A

[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


Save array A to a binary file in NumPy .npy format. In the example below the file is saved in the working directory. However, an arbitrary path can be specified in the string-parameter of _save()_.

In [136]:
np.save("binFileA",A)

Load array, which has been saved to a binary file into NumPy:

In [137]:
AL=np.load("binFileA.npy")
print AL

[[2 3 0 1]
 [4 2 6 0]
 [5 1 6 2]]


Save array to a text-file. Note that _savetxt()_ also has parameters for separating columns (_delimiter=''_) and lines (_newline='\n'_). Thus this method and the corresponding _loadtxt()_-method can also be applied for writing to and reading from .csv.

Load data from a textfile into a NumPy array:

In [138]:
np.savetxt("textFileA",A,fmt="%4.2f")

In [139]:
AT=np.loadtxt("textFileA")
print AT

[[ 2.  3.  0.  1.]
 [ 4.  2.  6.  0.]
 [ 5.  1.  6.  2.]]


## Exercises