# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Basic-Data-Types" data-toc-modified-id="Basic-Data-Types-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basic Data Types</a></div><div class="lev2 toc-item"><a href="#Vectors" data-toc-modified-id="Vectors-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Vectors</a></div><div class="lev3 toc-item"><a href="#Define-vectors" data-toc-modified-id="Define-vectors-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Define vectors</a></div><div class="lev3 toc-item"><a href="#Access-vector-components" data-toc-modified-id="Access-vector-components-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>Access vector components</a></div><div class="lev3 toc-item"><a href="#Simple-operations-on-vectors" data-toc-modified-id="Simple-operations-on-vectors-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>Simple operations on vectors</a></div><div class="lev3 toc-item"><a href="#Set-operations" data-toc-modified-id="Set-operations-1.1.4"><span class="toc-item-num">1.1.4&nbsp;&nbsp;</span>Set operations</a></div><div class="lev3 toc-item"><a href="#Sampling-and-sorting" data-toc-modified-id="Sampling-and-sorting-1.1.5"><span class="toc-item-num">1.1.5&nbsp;&nbsp;</span>Sampling and sorting</a></div><div class="lev2 toc-item"><a href="#Matrices" data-toc-modified-id="Matrices-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Matrices</a></div><div class="lev3 toc-item"><a href="#Matrix-construction-1" data-toc-modified-id="Matrix-construction-1-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Matrix construction 1</a></div><div class="lev3 toc-item"><a href="#Accessing-matrix-elements" data-toc-modified-id="Accessing-matrix-elements-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Accessing matrix elements</a></div><div class="lev3 toc-item"><a href="#Define-row--and-column-names" data-toc-modified-id="Define-row--and-column-names-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Define row- and column-names</a></div><div class="lev3 toc-item"><a href="#Matrix-construction-2" data-toc-modified-id="Matrix-construction-2-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>Matrix construction 2</a></div><div class="lev3 toc-item"><a href="#Operations-on-matrices" data-toc-modified-id="Operations-on-matrices-1.2.5"><span class="toc-item-num">1.2.5&nbsp;&nbsp;</span>Operations on matrices</a></div><div class="lev4 toc-item"><a href="#Elementwise-multiplication" data-toc-modified-id="Elementwise-multiplication-1.2.5.1"><span class="toc-item-num">1.2.5.1&nbsp;&nbsp;</span>Elementwise multiplication</a></div><div class="lev4 toc-item"><a href="#Matrix-multiplication" data-toc-modified-id="Matrix-multiplication-1.2.5.2"><span class="toc-item-num">1.2.5.2&nbsp;&nbsp;</span>Matrix multiplication</a></div><div class="lev4 toc-item"><a href="#Transpose-of-a-matrix" data-toc-modified-id="Transpose-of-a-matrix-1.2.5.3"><span class="toc-item-num">1.2.5.3&nbsp;&nbsp;</span>Transpose of a matrix</a></div><div class="lev4 toc-item"><a href="#Extract-diagonal-elements-of-a-matrix" data-toc-modified-id="Extract-diagonal-elements-of-a-matrix-1.2.5.4"><span class="toc-item-num">1.2.5.4&nbsp;&nbsp;</span>Extract diagonal elements of a matrix</a></div><div class="lev4 toc-item"><a href="#Create-diagonal-matrix" data-toc-modified-id="Create-diagonal-matrix-1.2.5.5"><span class="toc-item-num">1.2.5.5&nbsp;&nbsp;</span>Create diagonal matrix</a></div><div class="lev4 toc-item"><a href="#Inverse-Matrix" data-toc-modified-id="Inverse-Matrix-1.2.5.6"><span class="toc-item-num">1.2.5.6&nbsp;&nbsp;</span>Inverse Matrix</a></div><div class="lev4 toc-item"><a href="#Solve-system-of-linear-equations" data-toc-modified-id="Solve-system-of-linear-equations-1.2.5.7"><span class="toc-item-num">1.2.5.7&nbsp;&nbsp;</span>Solve system of linear equations</a></div><div class="lev2 toc-item"><a href="#Lists" data-toc-modified-id="Lists-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Lists</a></div><div class="lev2 toc-item"><a href="#Data-Frame" data-toc-modified-id="Data-Frame-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Data Frame</a></div><div class="lev3 toc-item"><a href="#Import-data-into-data-frame" data-toc-modified-id="Import-data-into-data-frame-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Import data into data frame</a></div>

# Basic Data Types
* Author: Johannes Maucher
* Last Update: 2017-10-03

## Vectors

In R a vector is a sequence of elements. All elements must be of the same basic type. The elements of a vector are called *components*.

### Define vectors

In [29]:
(x<-6)
class(x)

[1] 6

[1] "numeric"

In [30]:
(x<-1:13)
class(x)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13

[1] "integer"

In [37]:
(x<-integer(5))
class(x)
(x<-numeric(5))
class(x)

[1] 0 0 0 0 0

[1] "integer"

[1] 0 0 0 0 0

[1] "numeric"

In [38]:
(x <- seq(1,30,4))

[1]  1  5  9 13 17 21 25 29

In [39]:
(x<-rep(3,5))
(x<-rep(1:7,3))

[1] 3 3 3 3 3

[1] 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7

In [8]:
y <- c(100,200,50,-10)
y
class(y)

[1] 100 200  50 -10

[1] "numeric"

In [9]:
z <- c("last","in","first","out")
class(z)

[1] "character"

In [10]:
customer <- c(37,61000,250000,70000)
featureNames <- c("age","income","capital","credit")
names(customer) <- featureNames
customer

age  income capital  credit 
     37   61000  250000   70000

### Access vector components

Filter by index:

In [ ]:
z[1]

Get all elements except those specified in a negative index:

In [46]:
z[-1]
z[-3]

[1] "in"    "first" "out"

[1] "last" "in"   "out"

In [47]:
print(z[-3])

[1] "last" "in"   "out" 


Get type of vector components:

In [48]:
print(z[0])

character(0)


Filter by name of component:

In [49]:
customer["age"]

age 
 37

Filter by set of indices:

In [23]:
customer[2:3]

income capital 
  61000  250000

In [25]:
customer[c(1,4)]

age credit 
    37  70000

In [50]:
customer[c("age","credit")]

age credit 
    37  70000

Filter by mask

In [12]:
rel <- c(FALSE,TRUE,TRUE,FALSE)
customer[rel]

income capital 
  61000  250000

Filter by value:

In [44]:
y
y[y<100]

[1] 100 200  50 -10

[1]  50 -10

Elements of different type can be assigned to a vector. However, all different types are mapped to a single type, i.e. after assignment all elements of the vector are of same type. 

In [51]:
mix <- c(1,6,8,TRUE)
mix
class(mix)
mix2 <- c(1,6,8,TRUE,"word")
mix2
class(mix2)

[1] 1 6 8 1

[1] "numeric"

[1] "1"    "6"    "8"    "TRUE" "word"

[1] "character"

### Simple operations on vectors

In [52]:
(a <- c(3,9,18))
(f <- c(1/3,2/3,5/3))
(r<-a*f)

[1]  3  9 18

[1] 0.3333333 0.6666667 1.6666667

[1]  1  6 30

In [53]:
(t<-a+r)
sum(t)

[1]  4 15 48

[1] 67

### Set operations

In [7]:
a<-seq(1,20,3)
a
b<-1:10
b
c<-rep(c(1,5,8),3)
c

[1]  1  4  7 10 13 16 19

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1 5 8 1 5 8 1 5 8

In [8]:
print("Elements of a, which are contained in b:")
a %in% b
print("Elements of b, which are contained in a:")
b %in% a

[1] "Elements of a, which are contained in b:"


[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE

[1] "Elements of b, which are contained in a:"


[1]  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE

In [9]:
print("Unique elements of c:")
unique(c)
print("Union of a and b:")
union(a,b)
print("Intersection of a and b:")
intersect(a,b)
print("Elements, which are in b but not in a:")
setdiff(b,a)

[1] "Unique elements of c:"


[1] 1 5 8

[1] "Union of a and b:"


[1]  1  4  7 10 13 16 19  2  3  5  6  8  9

[1] "Intersection of a and b:"


[1]  1  4  7 10

[1] "Elements, which are in b but not in a:"


[1] 2 3 5 6 8 9

### Sampling and sorting

In [10]:
d<-1:48
set.seed(134)
print("Sample 6 out of 48 without replacement:")
sample(d,6)
print("Sample 6 out of 48 with replacement:")
sample(d,6,replace=T)

[1] "Sample 6 out of 48 without replacement:"


[1] 10 30 41 12 27  8

[1] "Sample 6 out of 48 with replacement:"


[1] 18 38  5 40 36  5

In [11]:
s<-sample(d,15,replace=T)
print("Sample 15 out of 48 with replacement:")
s
print("Reverse order of elements:")
rev(s)
print("Sort sample in increasing order:")
sort(s)
print("Sort sample in decreasing order:")
sort(s,decreasing=T)
print("Original position of items in increasing order")
order(s)
print("Sort sample via order-function (same result as above):")
s[order(s)]


[1] "Sample 15 out of 48 with replacement:"


[1] 47 34 23 27 29 42 44 26 43 28  2  6 35 21 31

[1] "Reverse order of elements:"


[1] 31 21 35  6  2 28 43 26 44 42 29 27 23 34 47

[1] "Sort sample in increasing order:"


[1]  2  6 21 23 26 27 28 29 31 34 35 42 43 44 47

[1] "Sort sample in decreasing order:"


[1] 47 44 43 42 35 34 31 29 28 27 26 23 21  6  2

[1] "Original position of items in increasing order"


[1] 11 12 14  3  8  4 10  5 15  2 13  6  9  7  1

[1] "Sort sample via order-function (same result as above):"


[1]  2  6 21 23 26 27 28 29 31 34 35 42 43 44 47

## Matrices
In R a matrix is a 2-dimensional collection of elements. All elements must be of the same basic type.

### Matrix construction 1

In [12]:
vec <- 20:39
length(vec)

[1] 20

In [13]:
matC <- matrix(vec,nrow=4,ncol=5)
matC

[,1] [,2] [,3] [,4] [,5]
[1,] 20   24   28   32   36  
[2,] 21   25   29   33   37  
[3,] 22   26   30   34   38  
[4,] 23   27   31   35   39

In [14]:
matR <- matrix(vec,nrow=4,ncol=5,byrow = TRUE)
matR

[,1] [,2] [,3] [,4] [,5]
[1,] 20   21   22   23   24  
[2,] 25   26   27   28   29  
[3,] 30   31   32   33   34  
[4,] 35   36   37   38   39

In [15]:
matO <- matrix(vec,nrow=4,ncol=10)
matO

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 20   24   28   32   36   20   24   28   32   36   
[2,] 21   25   29   33   37   21   25   29   33   37   
[3,] 22   26   30   34   38   22   26   30   34   38   
[4,] 23   27   31   35   39   23   27   31   35   39

In [16]:
matP<- matrix(vec,nrow=4,ncol=3)
matP

Warning message in matrix(vec, nrow = 4, ncol = 3):
"Datenlänge [20] ist kein Teiler oder Vielfaches der Anzahl der Spalten [3]"

[,1] [,2] [,3]
[1,] 20   24   28  
[2,] 21   25   29  
[3,] 22   26   30  
[4,] 23   27   31

### Accessing matrix elements

In [17]:
matR[2,4]
matR[1:2,3:5]
matR[1:2,c(1,3,4)]
matR[,2]
matR[3,]
matR[c(4,1),]

[1] 28

[,1] [,2] [,3]
[1,] 22   23   24  
[2,] 27   28   29

[,1] [,2] [,3]
[1,] 20   22   23  
[2,] 25   27   28

[1] 21 26 31 36

[1] 30 31 32 33 34

[,1] [,2] [,3] [,4] [,5]
[1,] 35   36   37   38   39  
[2,] 20   21   22   23   24

In [18]:
print(matR)

     [,1] [,2] [,3] [,4] [,5]
[1,]   20   21   22   23   24
[2,]   25   26   27   28   29
[3,]   30   31   32   33   34
[4,]   35   36   37   38   39


### Define row- and column-names

In [19]:
dimnames(matR) <- list(c("r1","r2","r3","r4"),c("c1","c2","c3","c4","c5"))
print(matR)

   c1 c2 c3 c4 c5
r1 20 21 22 23 24
r2 25 26 27 28 29
r3 30 31 32 33 34
r4 35 36 37 38 39


In [20]:
matR["r1","c3"]

[1] 22

### Matrix construction 2
Combine matrices horizontally by *rbind( )* and vertically by *cbind( )*. 

In [21]:
customer <- c(37,61000,250000,70000)
featureNames <- c("age","income","capital","credit")
names(customer) <- featureNames
customer

age  income capital  credit 
     37   61000  250000   70000

In [22]:
custMat <- matrix(customer,nrow=1,ncol=4,byrow = TRUE)
print(custMat)

     [,1]  [,2]   [,3]  [,4]
[1,]   37 61000 250000 70000


In [23]:
customer2 <- c(51,134600,750000,90000)
featureNames <- c("age","income","capital","credit")
names(customer2) <- featureNames
customer2
custMat2 <- matrix(customer2,nrow=1,ncol=4,byrow = TRUE)

age  income capital  credit 
     51  134600  750000   90000

In [24]:
allCust <- rbind(custMat,custMat2)
print(allCust)

     [,1]   [,2]   [,3]  [,4]
[1,]   37  61000 250000 70000
[2,]   51 134600 750000 90000


In [25]:
allCust <- rbind(allCust,allCust)
print(allCust)

     [,1]   [,2]   [,3]  [,4]
[1,]   37  61000 250000 70000
[2,]   51 134600 750000 90000
[3,]   37  61000 250000 70000
[4,]   51 134600 750000 90000


Serialization of a matrix, column-by-column:

In [26]:
c(allCust)

[1]     37     51     37     51  61000 134600  61000 134600 250000 750000
[11] 250000 750000  70000  90000  70000  90000

### Operations on matrices

Define some matrices for demonstration of matrix-operations:

In [27]:
(A<-matrix(seq(1,6),nrow=2,ncol=3))

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [28]:
(B<-matrix(seq(1,6),nrow=2,ncol=3,byrow = T))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [29]:
(C<-matrix(seq(1,6),nrow=3,ncol=2,byrow = T))

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [30]:
(D<-matrix(seq(1,9),nrow=3))

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

#### Elementwise multiplication

In [31]:
A*B

[,1] [,2] [,3]
[1,] 1     6   15  
[2,] 8    20   36

#### Matrix multiplication

In [32]:
A %*% C

[,1] [,2]
[1,] 35   44  
[2,] 44   56

#### Transpose of a matrix

In [33]:
A
t(A)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

#### Extract diagonal elements of a matrix

In [34]:
diag(D)

[1] 1 5 9

#### Create diagonal matrix

In [35]:
diag(rep(1,4))

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

#### Inverse Matrix

In [36]:
set.seed(123)
(E<-matrix(floor(10*runif(9)),nrow=3))

[,1] [,2] [,3]
[1,] 2    8    5   
[2,] 7    9    8   
[3,] 4    0    5

In [37]:
(F<-solve(E))

[,1]        [,2]       [,3]      
[1,] -0.39473684  0.3508772 -0.1666667
[2,]  0.02631579  0.0877193 -0.1666667
[3,]  0.31578947 -0.2807018  0.3333333

In [38]:
E %*% F

[,1]          [,2]          [,3]
[1,]  1.000000e+00  0.000000e+00 0   
[2,]  0.000000e+00  1.000000e+00 0   
[3,] -2.220446e-16 -2.220446e-16 1

#### Solve system of linear equations
A system of linear equations, can be written as a matrix-multiplication, with known matrix $C$ and vector $a$ and unknown vector $x$:
$$
\mathbf{a}=C \mathbf{x}
$$

$$
\left(
\begin{array}{c}
a_1\\
a_2\\
a_3\\
\end{array}
\right)
=
\left(
\begin{array}{ccc}
C_{11} & C_{12} & C_{13} \\
C_{21} & C_{22} & C_{23} \\
C_{31} & C_{32} & C_{33} \\
\end{array}
\right)
\cdot
\left(
\begin{array}{c}
x_1\\
x_2\\
x_3\\
\end{array}
\right)
$$

Vector $x$ can be determined by:

In [39]:
(C<-E)
(a<-c(7,15,9))

[,1] [,2] [,3]
[1,] 2    8    5   
[2,] 7    9    8   
[3,] 4    0    5

[1]  7 15  9

In [40]:
(x<-solve(C,a))

[1] 1 0 1

## Lists
In R lists are vectors, which can contain not only basic types (as vectors) but arbitrary objects.

In [41]:
tvec <- c(17,21,23,14)
wvec <- c("rainy","sunny","sunny","cloudy")
dvec <- c("monday","tuesday","wednesday","thursday")
yvec  <- 2016
wlist <- list(temp=tvec,weather=wvec,day=dvec,year=yvec)
print(wlist)

$temp
[1] 17 21 23 14

$weather
[1] "rainy"  "sunny"  "sunny"  "cloudy"

$day
[1] "monday"    "tuesday"   "wednesday" "thursday" 

$year
[1] 2016



In [42]:
wlist[1]
wlist["temp"]
wlist[2]
wlist["weather"]

$temp
[1] 17 21 23 14

$temp
[1] 17 21 23 14

$weather
[1] "rainy"  "sunny"  "sunny"  "cloudy"

$weather
[1] "rainy"  "sunny"  "sunny"  "cloudy"

Access vector-components of list-components: 

In [43]:
wlist[["temp"]][2]
wlist[["day"]][3]

[1] 21

[1] "wednesday"

In [44]:
wlist$temp
wlist$day[2]
wlist$year

[1] 17 21 23 14

[1] "tuesday"

[1] 2016

Flatten nested lists:

In [45]:
unlist(wlist)

temp1       temp2       temp3       temp4    weather1    weather2 
       "17"        "21"        "23"        "14"     "rainy"     "sunny" 
   weather3    weather4        day1        day2        day3        day4 
    "sunny"    "cloudy"    "monday"   "tuesday" "wednesday"  "thursday" 
       year 
     "2016"

## Data Frame
Data frames are applied for storing data tables. A data frame is a list of vectors of equal length.

In [46]:
df=data.frame(tvec,wvec,dvec)
print(df)

  tvec   wvec      dvec
1   17  rainy    monday
2   21  sunny   tuesday
3   23  sunny wednesday
4   14 cloudy  thursday


In [47]:
df[2,3]
df[2,"dvec"]
df["2","dvec"]

[1] tuesday
Levels: monday thursday tuesday wednesday

[1] tuesday
Levels: monday thursday tuesday wednesday

[1] tuesday
Levels: monday thursday tuesday wednesday

In [48]:
nrow(df)
ncol(df)

[1] 4

[1] 3

In [49]:
df[[3]]

[1] monday    tuesday   wednesday thursday 
Levels: monday thursday tuesday wednesday

In [50]:
df$dvec

[1] monday    tuesday   wednesday thursday 
Levels: monday thursday tuesday wednesday

In [51]:
df[,3]

[1] monday    tuesday   wednesday thursday 
Levels: monday thursday tuesday wednesday

In [52]:
df[3]

dvec     
1 monday   
2 tuesday  
3 wednesday
4 thursday

In [53]:
df[c("tvec","dvec")]

tvec dvec     
1 17   monday   
2 21   tuesday  
3 23   wednesday
4 14   thursday

In [54]:
df[2,]

tvec wvec  dvec   
2 21   sunny tuesday

In [55]:
df[c(2,4),]

tvec wvec   dvec    
2 21   sunny  tuesday 
4 14   cloudy thursday

In [56]:
df["1",]

tvec wvec  dvec  
1 17   rainy monday

In [57]:
F=df$wvec=="sunny"
F

[1] FALSE  TRUE  TRUE FALSE

In [58]:
df[F,]

tvec wvec  dvec     
2 21   sunny tuesday  
3 23   sunny wednesday

### Import data into data frame

In [59]:
energyData=read.csv(file="../data/EnergyMixGeoClust.csv", header=TRUE, sep=",",row.names=1)

In [60]:
print(energyData)

                Country   Oil   Gas   Coal Nuclear Hydro Total2009 CO2Emm
0                    US 842.9 588.7  498.0   190.2  62.2    2182.0 5941.9
1                Canada  97.0  85.2   26.5    20.3  90.2     319.2  602.7
2                Mexico  85.6  62.7    6.8     2.2   6.0     163.2  436.8
3             Argentina  22.3  38.8    1.1     1.8   9.2      73.3  164.2
4                Brazil 104.3  18.3   11.7     2.9  88.5     225.7  409.4
5                 Chile  15.4   3.0    4.1     0.0   5.6      28.1   70.3
6              Colombia   8.8   7.8    3.1     0.0   9.3      29.0   57.9
7               Ecuador   9.9   0.4    0.0     0.0   2.1      12.4   31.3
8                  Peru   8.5   3.1    0.5     0.0   4.5      16.6   35.5
9             Venezuela  27.4  26.8    0.0     0.0  19.5      73.6  147.0
10              Austria  13.0   8.4    2.3     0.0   8.3      32.0   68.8
11           Azerbaijan   2.8   6.9    0.0     0.0   0.5      10.2   24.8
12              Belarus   9.3  14.5   

In [61]:
energyData$Coal

[1]  498.0   26.5    6.8    1.1   11.7    4.1    3.1    0.0    0.5    0.0
[11]    2.3    0.0    0.0    4.6    6.3   15.8    4.0    3.7   10.1   71.0
[21]    7.9    2.5    0.1    1.3   13.4   33.0    0.2    7.9    0.3   53.9
[31]    3.6    6.2   82.9    3.6   10.6    1.6    0.1   27.2    0.0   35.0
[41]   29.7    1.4    1.4    0.0    0.0    0.0    0.0    0.7    1.1   99.4
[51]   50.8    0.4 1537.4    7.6  245.8   30.5  108.8    4.0    1.7    4.3
[61]    6.8    0.0   68.6   38.7   14.1

In [62]:
help(read.csv)